Feature/ own tasks screen
DoIt-Project/DoIt pull request #11
Opened 2021-11-20 22:09 UTC by danil-ivanov

2021-11-20 22:10 UTC, danil-ivanov commented
Экран своих задач + экран ленты друзей

2021-11-21 16:52 UTC, blackplayerten requested changes

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Extensions/Structures.swift
> +//  Structures.swift
файл должен располагаться в Model папке, а не в экстеншене

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Extensions/Structures.swift
> +    let creator: Int?
если это id создателя, то лучше написать creatorId, а то непонятно

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Extensions/UIImageExtension.swift
> +        static var standartImage: UIImage { UIImage(named: "standartImage")! }
обычно пишут defaultImage

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Extensions/UIImageExtension.swift
> +        static var isNotDone: UIImage { UIImage(named: "isNotDone")! }
done и notDone

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/ChapterCollectionView/ChapterCollectionCell.swift
> +        static let cornerRadius = 15.0
лучше у нейменга впереди добавить cell, так будет более читаемо

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/FeedController.swift
> +//  FeedController.swift
расположение фалов поменять на:
Views/Feed/CollectionView/FeedCollectionView.swift
Views/Feed/CollectionView/FeedCollectionViewCell.swift
и 
Views/Feed/FeedViewController.swift

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/FeedController.swift
> +        static let padding = 8.0
vcPadding

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/FeedController.swift
> +    var collection: FeedCollectionView = {
private

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/FeedController.swift
> +        collection.backgroundColor = .lightGray
у вас вроде lightGray забит в вашу структуру с цветами. если да, то лучше использовать цвета оттуда

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/MainTabBarController.swift
> +
лишняя пустая строка

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/MainTabBarController.swift
> +
убрать

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/MyTasksController.swift
> +class MyTasksController: UIViewController {
лучше UserTasksViewController и FriendsTasksViewController

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/ChapterCollectionView/ChapterCollectionCell.swift
> +    }
бессмысленно

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/ChapterCollectionView/ChapterCollectionCell.swift
> +    private func configureLayout() {
configureChapterLabel

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/ChapterCollectionView/ChapterCollectionCell.swift
> +    private func configureData(chapterData: Chapter) {
configureData(withChapter: Chapter)

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/ChapterCollectionView/ChapterCollectionView.swift
> +    var chapters = [Chapter(title: "Все задачи", color: .gray, textColor: .white),
private

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/ChapterCollectionView/ChapterCollectionView.swift
> +
убрать

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/FeedCollectionView/FeedCollectionCell.swift
> +class FeedCollectionCell: UICollectionViewCell {
CollectionView

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/FeedCollectionView/FeedCollectionCell.swift
> +        }
(image != nil) ? (taskImg = UIImage()) : (taskImg = UIImage())

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/FeedCollectionView/FeedCollectionCell.swift
> +    private func configureTaskLabel(titleText: String?) {
можно сделать не опционалом и в структуре тоже

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/FeedCollectionView/FeedCollectionCell.swift
> +        }
titleText.isEmpty ? (titleLabel.text = titleText) : (titleLabel.text = "default")

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/TasksTableView/TaskTableViewCell.swift
> +    static let identifier = "taskCell"
не обязательно

2021-11-21 16:52 UTC, blackplayerten commented on DoIt/Views/TasksTableView/TaskTableViewCell.swift
> +    private let indicator: UIView = {
loadingIndicator или progressIndicator?

2021-11-21 18:06 UTC, danil-ivanov commented on DoIt/Views/MyTasksController.swift
> +class MyTasksController: UIViewController {
Будет TasksViewController и FeedViewController

2021-11-23 11:02 UTC, blackplayerten requested changes

2021-11-23 11:02 UTC, blackplayerten commented on DoIt/Views/Tasks/TasksController.swift
> +        collectionView.dataSource = collectionView.self
просто self?

2021-11-23 11:02 UTC, blackplayerten commented on DoIt/Views/Tasks/TasksController.swift
> +    var table: TasksTableView = {
private

2021-11-23 11:02 UTC, blackplayerten commented on DoIt/Views/Tasks/TasksController.swift
> +    var collection: ChapterCollectionView = {
private

2021-11-23 11:02 UTC, blackplayerten commented on DoIt/Views/Tasks/TasksController.swift
> +        tableView.dataSource = tableView.self
self

2021-11-23 11:02 UTC, blackplayerten commented on DoIt/Views/Tasks/TasksTableView/TasksTableView.swift
> +        let cell = tableView.dequeueReusableCell(withIdentifier: "TableViewCell", for: indexPath) as? TaskTableViewCell
guard let

2021-11-23 11:02 UTC, blackplayerten commented on DoIt/Views/Tasks/TasksTableView/TasksTableView.swift
> +        return cell!
! уйдет после добавления guard

2021-11-23 14:14 UTC, danil-ivanov commented on DoIt/Models/Structures.swift
> +    let color: UIColor?
цвет тут вообще временно, пока не могу обращаться к разделу и из него брать цвет для индикатора

2021-12-01 07:36 UTC, blackplayerten approved these changes

2021-12-02 00:11 UTC, merged