Feature/search friends screen search screen was added
DoIt-Project/DoIt pull request #8
Opened 2021-11-05 18:52 UTC by rikine

2021-11-17 08:14 UTC, blackplayerten requested changes

2021-11-17 08:14 UTC, blackplayerten commented on DoIt/Views/Search Friends/SearchFriendsController.swift
> +            self.navigationItem.titleView?.layer.opacity = Constants.transparentValue
вынести в отдельную функцию

2021-11-17 08:14 UTC, blackplayerten commented on DoIt/Views/Search Friends/SearchFriendsController.swift
> +            self.navigationItem.rightBarButtonItem = self.openSearchButton
и это тоже, возможно сделать 1 функцию, а не 2

2021-11-17 11:36 UTC, rikine commented on DoIt/Views/Search Friends/FindFriendCell.swift
> +        static let followButtonUnselectedColor: UIColor = .AppColors.accentColor
А цвета вынести в extension с цветами, или просто задать когда присваиваю?

2021-11-17 11:38 UTC, rikine commented on DoIt/Views/Search Friends/FindFriendCell.swift
> +        static let followButtonAnimationScale: CGFloat = 0.9
Их получается просто в функцию вставить, где присваиваю эти переменные? Или числом просто написать?

2021-11-18 17:09 UTC, rikine commented on DoIt/Views/Search Friends/FindFriendCell.swift
> +        followButton.backgroundColor = isFollowed ? Constants.followButtonSelectedColor : Constants.followButtonUnselectedColor
?

2021-11-20 17:13 UTC, blackplayerten commented on DoIt/Views/Search Friends/FindFriendCell.swift
> +        static let followButtonAnimationScale: CGFloat = 0.9
просто числом

2021-11-20 17:14 UTC, blackplayerten commented on DoIt/Views/Search Friends/FindFriendCell.swift
> +        static let followButtonUnselectedColor: UIColor = .AppColors.accentColor
в экстеншн с цветами

2021-11-20 17:29 UTC, blackplayerten requested changes

2021-11-20 17:29 UTC, blackplayerten commented on DoIt/Models/SearchFriendsModel.swift
> +    let login: String?
думаю логин у пользователя не может быть пустым

2021-11-20 17:29 UTC, blackplayerten commented on DoIt/Views/Custom Views/Profile.swift
> +}
не делаем экстеншены от базовых классов
создаем свою UIView наследованную от UIView и там уже делаете с ней что хотите

2021-11-20 17:29 UTC, blackplayerten commented on DoIt/Views/Custom Views/Profile.swift
> +final class ProfileInformationCell: UIView {
это все должно быть в контроллере

2021-11-20 17:29 UTC, blackplayerten commented on DoIt/Views/Custom Views/Profile.swift
> +final class ProfileHeaderView: UIView {
перенести в соответствующий контроллер

2021-11-20 17:29 UTC, blackplayerten commented on DoIt/Views/Search Friends/SearchFriendsCell.swift
> +        configureFollowButton(isFollowed: model.isFollowed)
я бы поменяла на дидсеты вроде:
```
let summaryLabel: UILabel {
    didSet {
      guard oldValue != summaryLabel else { return }
    }
}
```

2021-11-20 17:54 UTC, blackplayerten requested changes

2021-11-20 17:54 UTC, blackplayerten commented on DoIt/Views/Custom Views/Profile.swift
> +        textLabel.bottomAnchor.constraint(equalTo: bottomAnchor, constant: -Constants.defaultOffset).isActive = true
это можно объединить через forEach

2021-11-20 17:54 UTC, blackplayerten commented on DoIt/Views/Custom Views/Profile.swift
> +    }
зачем? уже есть инит

2021-11-20 17:54 UTC, blackplayerten commented on DoIt/Views/Custom Views/Profile.swift
> +}
можно объединииь через forEach

2021-11-20 17:54 UTC, blackplayerten commented on DoIt/Views/Custom Views/Profile.swift
> +    }
это можно было в 1 функцию внести

2021-11-23 10:54 UTC, blackplayerten approved these changes

2021-11-23 10:54 UTC, blackplayerten commented on DoIt/Views/SignIn/SignInController.swift
> +class SignInController: UIViewController {
SignInViewController

2021-11-23 10:54 UTC, blackplayerten commented on DoIt/Views/SignUp/SignUpController.swift
> +class SignUpController: UIViewController {
SignUpViewController

2021-11-23 10:54 UTC, merged